### ISSUE TITLE
Divergence in the jsonrpc structs

### ISSUE THREAD

**Issue by Nuttymoon** [ava-labs/avalanche-types-rs#33]
Hi,

I am trying to use `avalanche_types::jsonrpc::platformvm` structs to query the P-Chain API using `ureq`. It seems that the provided structs don't match the newest versions of the API.

E.g. [ApiPrimaryValidator](https://docs.rs/avalanche-types/latest/avalanche_types/jsonrpc/platformvm/struct.ApiPrimaryValidator.html) should match the struct of [platform.getCurrentValidators](https://docs.avax.network/apis/avalanchego/apis/p-chain#platformgetcurrentvalidators) response. I am seeing that:
- There is a field not present in the API response: `staked`
- Some filed from the API are not present on the Rust side: `signer`, `delegatorCount`, `delegatorWeight`

When I look at the docs and commits of this repo, it seems that it is kind of auto-generated from the Go lib. Can we still manually contribute? If so, I might be able to update these structs, as well as add some missing ones (e.g. for the `platform.getSubnets` and `platform.getBlockchains` methods).

**Comment by gyuho** [comment]
Apologies for late response. Yes, some fields are missing, as I was adding them in a hurry :)

Please feel free to contribute if you would like to add more fields.

**Comment by Nuttymoon** [comment]
Hey @gyuho no worries. I will probably open PRs on this topic then!

**Comment by gyuho** [comment]
I believe this is resolved with your PR.

Please feel free to re-open.

**Comment by Nuttymoon** [comment]
Indeed, thanks.

I will create more precise issues if needed. I saw you already integrated some JSON RPC methods I mentioned in the latest versions!
