### ISSUE TITLE
tonic gRPC client connection is getting closed by GoAway

### ISSUE THREAD

**Issue by hexfusion** [ava-labs/avalanche-types-rs#96]
During testing it was found that the corrutabledb errored from a  `GOAWAY` send from the golang rpcdb gRPC server. Often times this is the result of the gRPC client and server not sharing/honoring the expected keep alive configurations. This issue covers setting up an e2e test which stress tests the rpcdb. We will also want to get debug logs from gRPC.

Rust gRPC client config
- https://github.com/ava-labs/avalanche-types-rs/blob/96f95627a7dc5f6ea5c750b772c472660195710b/src/subnet/rpc/utils/grpc.rs#L69-L78

Go gRPC server config
- https://github.com/ava-labs/avalanchego/blob/eb6e7973a900dc647d29a2da8e7a233ac0a5fe77/vms/rpcchainvm/grpcutils/server.go#L45-L59

Error
```
[2023-06-16T05:29:16Z ERROR avalanche_types::subnet::rpc::database::rpcdb::client] get request failed: Status { code: Internal, message: "h2 protocol error: http2 error: connection error received: not a result of an error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b"", NO_ERROR, Remote) }))) }
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "closed to avoid possible corruption, init error: h2 protocol error: http2 error: connection error received: not a result of an error" }', subnet/src/vm/mod.rs:1283:35
```

**Comment by hexfusion** [comment]
The fix is to ensure we are using the default_client config for rpcdb, which it currently is not.

https://github.com/ava-labs/avalanche-types-rs/blob/09e78f78064984103d2cc01ecddf0b1a628f7ac2/src/subnet/rpc/vm/server.rs#L110

https://github.com/ava-labs/avalanche-types-rs/blob/09e78f78064984103d2cc01ecddf0b1a628f7ac2/src/subnet/rpc/vm/server.rs#L150

**Comment by richardpringle** [comment]
🎉
